### ISSUE TITLE
Fix Games: Space Squash and Hyper Fighting

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#12]
I pressed START nothing happened
Space Squash (Japan)
Space Squash (Japan) [T-En by Feel & Greg Stevens & Benjamin Stevens & Thunderstruck v2.0]

Buzz Buzz Buzz...
Hyper Fighting (World) (Aftermarket) (Unl) (Pirate)
Hyper Fighting (World) (Beta) (Aftermarket) (Unl) (Pirate)

**Comment by SupernaviX** [comment]
Thank you for the report! I've fixed the issues with both and published a new release, it should be out in a day or two.

**Comment by SupernaviX** [comment]
It is out
