### ISSUE TITLE
Game stopped: Hyper Fighting

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#13]
Hyper Fighting (World) (Aftermarket) (Unl) (Pirate).vb
MD5: c2047a94dcb0db30794c8533ba625622
Versus Mode - Ryu - Start, Earth Stopped.
Arcade Mode ok

**Comment by SupernaviX** [comment]
Thanks for the report @AngelofMe!

It looks like Versus Mode is meant to be multiplayer, using the Link Cable. This emulator isn't emulating that right now. I _think_ that's possible to support over bluetooth just looking at data transfer speeds, but I'm not sure.

I think what I'm gonna do now is detect when games are _trying_ to use the link cable, and show a popup explaining that it isn't supported.
