### ISSUE TITLE
Extensions, Anaglyph preset, Palette, built-in Filepicker with search bar & On-screen Input Setup

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#15]
Extensions
.vb
.vboy
.bin

Anaglyph preset (restart)
(Off/red & blue/red & cyan/red & electric cyan/red & green/green & magenta/yellow & blue)
Anaglyph preset - Off
![off](https://user-images.githubusercontent.com/26894447/171176749-396cdfbb-78e1-46e0-bcd6-f3f97b377d8f.png)
Anaglyph preset - red & blue
![red blue](https://user-images.githubusercontent.com/26894447/171176783-98119277-e0fd-4705-87f3-5a066e763c58.png)
Anaglyph preset - red & cyan
![red cyan](https://user-images.githubusercontent.com/26894447/171176890-44d832b7-f64b-40d3-8396-f06836040b2a.png)
Anaglyph preset - red & electric cyan
![red electriccyan](https://user-images.githubusercontent.com/26894447/171177066-593bdaa5-135f-43cc-ac55-18ab80eb2204.png)
Anaglyph preset - red & green
![red green](https://user-images.githubusercontent.com/26894447/171177174-d57efffa-1ed4-451a-916f-0a9d13919b20.png)
Anaglyph preset - green & magenta
![green magenta](https://user-images.githubusercontent.com/26894447/171177276-3abdd4b6-c61f-4764-be7a-30a43e6daf67.png)
Anaglyph preset - yellow & blue
![yellow blue](https://user-images.githubusercontent.com/26894447/171177334-d4266af0-1466-4da8-97d6-92c2c26ad552.png)

enum
{
 ANAGLYPH_PRESET_DISABLED = 0,
 ANAGLYPH_PRESET_RED_BLUE,
 ANAGLYPH_PRESET_RED_CYAN,
 ANAGLYPH_PRESET_RED_ELECTRICCYAN,
 ANAGLYPH_PRESET_RED_GREEN,
 ANAGLYPH_PRESET_GREEN_MAGENTA,
 ANAGLYPH_PRESET_YELLOW_BLUE,
};

static const uint32 AnaglyphPreset_Colors[][2] =
{
 { 0, 0 },
 { 0xFF0000, 0x0000FF },
 { 0xFF0000, 0x00B7EB },
 { 0xFF0000, 0x00FFFF },
 { 0xFF0000, 0x00FF00 },
 { 0x00FF00, 0xFF00FF },
 { 0xFFFF00, 0x0000FF },
};

Palette (restart)
(black & red/black & white)
Palette - black & red
![black red](https://user-images.githubusercontent.com/26894447/171177773-46111323-0ff8-4cc0-a45a-ff1018f9cf4a.png)
Palette - black & white
![black white](https://user-images.githubusercontent.com/26894447/171177915-96bfa8ab-deeb-4e19-bc5a-afaf6d39bbcc.png)

Filepicker
also called File Selector/Chooser, file requester, or open and save dialog
Searchbar
search box, search field or search bar
![images](https://user-images.githubusercontent.com/26894447/171183638-847f88f2-459f-43de-9728-446ff90697ff.jpg)
this is a snes9x ex+ filepicker screenshot
[Robert Broglia's emulators repository](https://github.com/Rakashazi/emu-ex-plus-alpha) 

Fast-forward button

customize text & primary color (that red default)

**Comment by AngelofMe** [comment]
On-screen Input Setup
![Screenshot_20220531-212851_Trebuchet](https://user-images.githubusercontent.com/26894447/171189471-a38b4b54-5ad7-405a-83ae-5173fa598cc2.png)
![Screenshot_20220531-214618_Trebuchet](https://user-images.githubusercontent.com/26894447/171189481-306c7e6a-ce25-40c3-b75b-0a80cc1763f2.png)

**Comment by AngelofMe** [comment]
turbo buttons
L,R,A,B

**Comment by AngelofMe** [comment]
Screenshot Next Frame

**Comment by AngelofMe** [comment]
Screenshot Next Frame

**Comment by AngelofMe** [comment]
Options-Video
![Screenshot_20220601-105539_Trebuchet](https://user-images.githubusercontent.com/26894447/171318640-62912a92-f9da-44dd-9705-3241aabdbd9f.png)
Options-Audio
![Screenshot_20220601-105633_Trebuchet](https://user-images.githubusercontent.com/26894447/171318734-50c52d8f-0628-4dd4-80da-cd3a83afb88f.png)
Options-System
![Screenshot_20220601-105717_Trebuchet](https://user-images.githubusercontent.com/26894447/171318817-0a3b24a2-6669-4656-a126-893405f2005b.png)
Options-GUI
![Screenshot_20220601-105802_Trebuchet](https://user-images.githubusercontent.com/26894447/171318925-d2056866-9f54-48bc-8656-147754fec753.png)
Options-File Paths
Save: (Select Folder/Same As Content/App Folder)
Screenshot:like Save Path, but it has a separate directory
for example
App Folder
Save (vvb/saves)
Screenshot (vvb/screenshots)

**Comment by AngelofMe** [comment]
Options-GUI
![Screenshot_20220608-100411_Trebuchet](https://user-images.githubusercontent.com/26894447/172515702-0354af82-7a9f-41ca-88e3-b486cd4f4071.png)

**Comment by AngelofMe** [comment]
Filepicker with Slide Bar
Slider or Slide Bar

**Comment by AngelofMe** [comment]
Filepicker with Slide Bar
Slider or Slide Bar

**Comment by SupernaviX** [comment]
So I've been looking into this, and I think that any kind of "custom" filepicker is impossible in modern android. Robert Broglia's emulators target [Android SDK version 30](https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/imagine/src/base/android/imagine-v9/build.gradle#L25), but mine targets 31. In version 31, every filepicker library I've found stops working, because apps are required to use the Storage Access Framework which filepickers are apparently incompatible with. Starting in [November 2022](https://developer.android.com/google/play/requirements/target-sdk), you won't be able to release updates unless your app targets SDK 31 or newer. The zsnes family of emulators will eventually get bit by this too, even [dolphin](https://dolphin-emu.org/blog/2021/02/11/dolphin-progress-report-december-2020-and-january-2021/#50-13386-use-storage-access-framework-scoped-storage-for-the-gamelist-on-android-by-josjuice) will. 

But moar extensions make sense and I'll push those up today, and anaglyph presets make sense so I'll figure out how to do that 🔜
