### ISSUE TITLE
3D Mode

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#17]
"Select the 3D mode. 
Anaglyph - used in conjunction with classic dual-lens-color glasses. 
Cyberscope - intended for use with the CyberScope 3D device. 
sidebyside - the left-eye image is displayed on the left, and the right-eye image is displayed on the right. 
vli - Vertical lines alternate between left and right view. 
hli - Horizontal lines alternate between left and right view.",
      {
         { "anaglyph",  NULL },
         { "cyberscope",  NULL },
         { "side-by-side",  NULL },
         { "vli", NULL},
         { "hli", NULL},

**Comment by SupernaviX** [comment]
What on earth is a cyberscope

**Comment by AngelofMe** [comment]
> What on earth is a cyberscope
http://www.goliathindustries.com/vb/VB3D.html
If you don't know what's that
https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro.cpp

https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro_core_options.h
Ctrl + F "cyberscope"

**Comment by AngelofMe** [comment]
> > What on earth is a cyberscope
> 
> http://www.goliathindustries.com/vb/VB3D.html If you don't know what's that https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro.cpp
> 
> https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro_core_options.h Ctrl + F "cyberscope"

Ctrl + F "CSCOPE"
https://github.com/libretro/beetle-vb-libretro/blob/master/libretro.cpp
   VB_Power();

   EmulatedVB.nominal_width        = 384;
   EmulatedVB.nominal_height       = 224;
   EmulatedVB.fb_width             = 384;
   EmulatedVB.fb_height            = 224;

   switch(VB3DMode)
   {
      case VB3DMODE_VLI:
         EmulatedVB.nominal_width  = 768 * prescale;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 768 * prescale;
         EmulatedVB.fb_height      = 224;
         break;

      case VB3DMODE_HLI:
         EmulatedVB.nominal_width  = 384;
         EmulatedVB.nominal_height = 448 * prescale;
         EmulatedVB.fb_width       = 384;
         EmulatedVB.fb_height      = 448 * prescale;
         break;

      case VB3DMODE_CSCOPE:
         EmulatedVB.nominal_width  = 512;
         EmulatedVB.nominal_height = 384;
         EmulatedVB.fb_width       = 512;
         EmulatedVB.fb_height      = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         EmulatedVB.nominal_width  = 384 * 2 + sbs_separation;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 384 * 2 + sbs_separation;
         EmulatedVB.fb_height      = 224;
         break;
      default:
         break;
   }
   EmulatedVB.lcm_width            = EmulatedVB.fb_width;
   EmulatedVB.lcm_height           = EmulatedVB.fb_height;

https://github.com/libretro/beetle-vb-libretro/blob/master/mednafen/vb/vip.c
   switch(VB3DMode)
   {
      default:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_VLI:
         espec->DisplayRect.w = 768 * VBPrescale;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_HLI:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 448 * VBPrescale;
         break;

      case VB3DMODE_CSCOPE:
         espec->DisplayRect.w = 512;
         espec->DisplayRect.h = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         espec->DisplayRect.w = 768 + VBSBS_Separation;
         espec->DisplayRect.h = 224;
         break;
   }

**Comment by AngelofMe** [comment]
> > What on earth is a cyberscope
> 
> http://www.goliathindustries.com/vb/VB3D.html If you don't know what's that https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro.cpp
> 
> https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro_core_options.h Ctrl + F "cyberscope"

Ctrl + F "CSCOPE"
https://github.com/libretro/beetle-vb-libretro/blob/master/libretro.cpp
   VB_Power();

   EmulatedVB.nominal_width        = 384;
   EmulatedVB.nominal_height       = 224;
   EmulatedVB.fb_width             = 384;
   EmulatedVB.fb_height            = 224;

   switch(VB3DMode)
   {
      case VB3DMODE_VLI:
         EmulatedVB.nominal_width  = 768 * prescale;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 768 * prescale;
         EmulatedVB.fb_height      = 224;
         break;

      case VB3DMODE_HLI:
         EmulatedVB.nominal_width  = 384;
         EmulatedVB.nominal_height = 448 * prescale;
         EmulatedVB.fb_width       = 384;
         EmulatedVB.fb_height      = 448 * prescale;
         break;

      case VB3DMODE_CSCOPE:
         EmulatedVB.nominal_width  = 512;
         EmulatedVB.nominal_height = 384;
         EmulatedVB.fb_width       = 512;
         EmulatedVB.fb_height      = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         EmulatedVB.nominal_width  = 384 * 2 + sbs_separation;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 384 * 2 + sbs_separation;
         EmulatedVB.fb_height      = 224;
         break;
      default:
         break;
   }
   EmulatedVB.lcm_width            = EmulatedVB.fb_width;
   EmulatedVB.lcm_height           = EmulatedVB.fb_height;

https://github.com/libretro/beetle-vb-libretro/blob/master/mednafen/vb/vip.c
   switch(VB3DMode)
   {
      default:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_VLI:
         espec->DisplayRect.w = 768 * VBPrescale;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_HLI:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 448 * VBPrescale;
         break;

      case VB3DMODE_CSCOPE:
         espec->DisplayRect.w = 512;
         espec->DisplayRect.h = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         espec->DisplayRect.w = 768 + VBSBS_Separation;
         espec->DisplayRect.h = 224;
         break;
   }

**Comment by AngelofMe** [comment]
> > What on earth is a cyberscope
> 
> http://www.goliathindustries.com/vb/VB3D.html If you don't know what's that https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro.cpp
> 
> https://raw.githubusercontent.com/libretro/beetle-vb-libretro/master/libretro_core_options.h Ctrl + F "cyberscope"

Ctrl + F "CSCOPE"
https://github.com/libretro/beetle-vb-libretro/blob/master/libretro.cpp
   VB_Power();

   EmulatedVB.nominal_width        = 384;
   EmulatedVB.nominal_height       = 224;
   EmulatedVB.fb_width             = 384;
   EmulatedVB.fb_height            = 224;

   switch(VB3DMode)
   {
      case VB3DMODE_VLI:
         EmulatedVB.nominal_width  = 768 * prescale;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 768 * prescale;
         EmulatedVB.fb_height      = 224;
         break;

      case VB3DMODE_HLI:
         EmulatedVB.nominal_width  = 384;
         EmulatedVB.nominal_height = 448 * prescale;
         EmulatedVB.fb_width       = 384;
         EmulatedVB.fb_height      = 448 * prescale;
         break;

      case VB3DMODE_CSCOPE:
         EmulatedVB.nominal_width  = 512;
         EmulatedVB.nominal_height = 384;
         EmulatedVB.fb_width       = 512;
         EmulatedVB.fb_height      = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         EmulatedVB.nominal_width  = 384 * 2 + sbs_separation;
         EmulatedVB.nominal_height = 224;
         EmulatedVB.fb_width       = 384 * 2 + sbs_separation;
         EmulatedVB.fb_height      = 224;
         break;
      default:
         break;
   }
   EmulatedVB.lcm_width            = EmulatedVB.fb_width;
   EmulatedVB.lcm_height           = EmulatedVB.fb_height;

https://github.com/libretro/beetle-vb-libretro/blob/master/mednafen/vb/vip.c
   switch(VB3DMode)
   {
      default:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_VLI:
         espec->DisplayRect.w = 768 * VBPrescale;
         espec->DisplayRect.h = 224;
         break;

      case VB3DMODE_HLI:
         espec->DisplayRect.w = 384;
         espec->DisplayRect.h = 448 * VBPrescale;
         break;

      case VB3DMODE_CSCOPE:
         espec->DisplayRect.w = 512;
         espec->DisplayRect.h = 384;
         break;

      case VB3DMODE_SIDEBYSIDE:
         espec->DisplayRect.w = 768 + VBSBS_Separation;
         espec->DisplayRect.h = 224;
         break;
   }

**Comment by SupernaviX** [comment]
I'm still a little bit confused.

It looks like the cyberscope is something from 1994 which you attached to a big ol' monitor to see things in 3D. I don't think there's any Android devices with a screen compatible with that.
And which devices would the vertical/horizontal interleaved options work with?

I don't think these would be that hard to throw in, but would they be useful to anyone? There's already 5 video modes (cardboard, anaglyph, side-by-side, left eye, right eye), I'm wary of adding more options and making it harder to set up unless someone has a use for them.
