### ISSUE TITLE
import verified files to emulator game list

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#18]
like StoicGoose - a wonderswan color emulator
https://github.com/xdanieldzd/StoicGoose/tree/master/StoicGoose/Assets/No-Intro
No-Intro .dat files make emulator recognize game files easily
game name
description
rom name
size
crc
md5
sha1
serial

you can download latest no-intro .dat files from dat-o-matic
https://datomatic.no-intro.org/index.php?page=download&op=dat&s=15
all default - prepare - download - extract .dat file from .zip file

Games/Virtual Boy/Golf (USA).zip/Golf (USA).vb
Games/Virtual Boy/V-Tetris (Japan).zip/V-Tetris (Japan).vb
1
Refresh ROMs (Emulator)
Select a ROM file or an entire folder to scan (zip/7zip/vb/vboy/bin files supported)
Select File/Folder
Search zip files
Scan subdirectories
2
Files (System App)
Games/Virtual Boy
Use this folder
3
Computing md5/crc/sha (no intro .dat files)
4
Library (Emulator)
Golf (USA)
V-Tetris (Japan)
![Screenshot_20220613-211152_Trebuchet](https://user-images.githubusercontent.com/26894447/173365282-84a04feb-1fa8-45f8-8e2c-c3446c568677.png)
![Screenshot_20220613-211203_Trebuchet](https://user-images.githubusercontent.com/26894447/173365306-207ccd15-d7f1-4bd9-98c8-a69fbfbe8937.png)
![Screenshot_20220613-211229_Trebuchet](https://user-images.githubusercontent.com/26894447/173365859-0b948441-adbd-4db2-be24-e8e3d5ef60a8.png)

**Comment by SupernaviX** [comment]
Neat! A "game list" would be useful as something to display on TVs too
