### ISSUE TITLE
Recent Games - Clear List

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#19]
why I think it's useful?
Rename
Waterworld (USA).vb to Golf (USA).vb
Somebody sent me a file Golf (USA).vb
but it's Waterworld (USA) actually
![image1](https://user-images.githubusercontent.com/26894447/173370714-8c6444fb-d3da-4a28-9293-d92401005c54.png)
![Screenshot_20220613-214914_Trebuchet](https://user-images.githubusercontent.com/26894447/173370769-2ae226cc-50b6-4ac4-90aa-950673e556f0.png)
![Screenshot_20220613-215140_Trebuchet](https://user-images.githubusercontent.com/26894447/173370828-054bf0fa-c7c9-40f4-8ed5-763fab56f33d.png)
![Screenshot_20220613-215158_Trebuchet](https://user-images.githubusercontent.com/26894447/173371493-8bc298f7-2a77-482a-b4cd-fd62d05fbb80.png)

**Comment by SupernaviX** [comment]
Sounds easy enough! Would you expect it to also delete save data, or just clear the list?
