### ISSUE TITLE
would you be interested in a pull request to merge in my litbyleia support fork?

### ISSUE THREAD

**Issue by jakedowns** [SupernaviX/vvb#21]
as i'm merging latest upstream/main into my fork, i'm wondering if there's any chance you'd want to merge my litbyleia support, or perhaps implement it in your own preferred way, that way users could enjoy your future improvements faster than waiting for me to update my fork.

there's a few users over on the LeiaForums who really love using your emulator on a stereoscopic display:

https://forums.leialoft.com/t/beta-release-3ds-virtual-boy-emulator-support-for-lumepad-red-hydrogen-one/1309/68

:) 

PS) it might be cool to see about a PC version that could work with LookingGlass monitors

**Comment by jakedowns** [comment]
![image](https://user-images.githubusercontent.com/1683122/173701690-152034df-a649-4784-aa01-ebc75c263346.png)

running into this error when trying to compile after modifying my leia.rs to match your latest changes :G 

![image](https://user-images.githubusercontent.com/1683122/173701794-62442f60-b76f-41f8-89f5-12229d16e59e.png)

**Comment by SupernaviX** [comment]
Hey! I'd definitely be open to merging the fork. Looking at [the LeiaPad license](https://www.leiainc.com/legal/license-agreement), it looks like even though it's closed source they're fine with the library getting used in open-source software. 

I've got some questions/comments but I'll leave em on the PR

**Comment by jakedowns** [comment]
awesome. one thing i noticed with my most recent build is that it seems like occasionally the left and right images get reversed. and then the 3d effect kind of pushes into the screen instead of popping out

im not sure if its something with my shader setup, or something else that changed in the rendering pipeline. 

have you experienced this kind of a thing with the anaglyph renderer?

**Comment by jakedowns** [comment]
![image](https://user-images.githubusercontent.com/1683122/173941159-ceb4d932-00a8-4b26-8921-37c704b359d6.png)

re: leia's appstore

**Comment by jakedowns** [comment]
@SupernaviX I sent you an email with my discord username if you wanna chat directly :)
