### ISSUE TITLE
Japanese Translation and a suggestion

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#28]
I don't know if my translation skills are good or not.
I translated this file into Japanese.
Rename txt -> xml
vvb/app/src/main/res/values/strings.xml
Could you please release .apk files on Github or F-Droid?
I flashed LineageOS, uninstalled all Google Apps AKA GApps
I can only download the latest VVB on Google Play
Some sites (APKPure) only offer XAPK, or (APK mirror) can't find VVB at all
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-ja/strings.xml
#29

**Comment by AngelofMe** [comment]
<resources>
    <string name="app_name">バーチャルバーチャルボーイ</string>
    <string name="main_menu_game_actions">ゲームアクション</string>
    <string name="main_menu_now_playing">再生中</string>
    <string name="main_menu_load_game">ゲームの読み込み</string>
    <string name="main_menu_onscreen_input_setup">画面上の入力設定</string>
    <string name="main_menu_controller_setup">コントローラーのセットアップ</string>
    <string name="main_menu_video_setup">ビデオ設定</string>
    <string name="main_menu_audio_setup">オーディオ設定</string>
    <string name="load_game_from_file">ファイルから読み込む</string>
    <string name="load_game_from_file_explanation">バーチャルボーイゲームのROMをダウンロードし、ここに読み込んでプレイできます。\ nプラネットバーチャルボーイの無料ROMは、https：//www.virtual-boy.com/homebrewで見つけることができます。 /.</string>
    <string name="load_game_from_file_explanation_button"> OK </ string>
    <string name="load_game_recent_games">最近のゲーム</string>
    <string name="load_game_no_recent_games">まだゲームをプレイしていません。試してみてください！</ string>
    <string name="load_game_bundled_games">バンドルされたゲーム</string>
    <string name="load_game_no_bundled_games">バンドルされたゲームはありません</string>
    <string name="load_game_created_by">％1$sによって作成</string>
    <string name="game_menu_resume_game">ゲームを再開</string>
    <string name="game_menu_reset_game">リセット</string>
    <string name="game_menu_auto_save">自動保存</string>
    <string name="game_menu_save_state">状態を保存</string>
    <string name="game_menu_load_state">ロード状態</string>
    <string name="game_menu_state_slot">現在の状態スロット</string>
    <string name="game_menu_state_slot_name">スロット％1 $ s </ string>
    <string name="game_menu_state_slot_empty">空</string>
    <string name="game_menu_state_slot_saved">保存済み：％1 $ s </ string>
    <string name="game_menu_close_game">ゲームを閉じる</string>
    <string name="onscreen_input_menu_on">仮想ゲームパッドを使用する</string>
    <string name="onscreen_input_menu_toggle_controls">トリガーボタンをトグルモードにする</string>
    <string name="onscreen_input_menu_haptic_feedback">ハプティックフィードバックを有効にする</string>
    <string name="onscreen_input_menu_parallax">視差</string>
    <string name="onscreen_input_menu_show_bounds">コントロール境界を表示</string>
    <string name="onscreen_input_menu_preview">プレビュー</string>
    <string name="controller_menu_controllers">コントローラー</string>
    <string name="controller_menu_manage">コントローラーの管理</string>
    <string name="controller_menu_automap_new_controller">新しいコントローラーの自動マップ</string>
    <string name="controller_menu_choose_controller">マップするコントローラーを選択</string>
    <string name="controller_menu_no_controllers_detected">コントローラーが検出されませんでした…</string>
    <string name="controller_menu_new_controller">新しいコントローラー</string>
    <string name="controller_menu_rename_controller">コントローラーの名前を変更</string>
    <string name="controller_menu_delete_controller">コントローラーの削除</string>
    <string name="controller_menu_name">コントローラー名？</ string>
    <string name="controller_menu_create">作成</string>
    <string name="controller_menu_cancel">キャンセル</string>
    <string name="controller_menu_rename">名前を変更</string>
    <string name="controller_menu_choose_rename">名前を変更するコントローラーを選択してください…</string>
    <string name="controller_menu_choose_delete">削除するコントローラーを選択してください…</string>
    <string name="controller_menu_default_name">コントローラー％1 $ d </ string>
    <string name="input_menu_dpad_left">左十字キー</string>
    <string name="input_menu_dpad_right">右の十字キー</string>
    <string name="input_menu_button_left">左</string>
    <string name="input_menu_button_right">右</string>
    <string name="input_menu_button_up">上</string>
    <string name="input_menu_button_down">下</string>
    <string name="input_menu_button_a"> A </ string>
    <string name="input_menu_button_b"> B </ string>
    <string name ="input_menu_button_lt">Lトリガー</string>
    <string name ="input_menu_button_rt">Rトリガー</string>
    <string name="input_menu_button_start">開始</string>
    <string name="input_menu_button_select">選択</string>
    <string name="input_menu_unmapped">マップされていない</string>
    <string name="input_menu_put_mapping">任意のコントロールを押して、この入力にマップします。長押しして複数のコントロールをマッピングします。</string>
    <string name="input_menu_add_mapping">任意のコントロールを押して、この入力に別のマッピングを追加します。</ string>
    <string name="video_menu_screen_zoom_percent">画面ズーム（パーセント）</ string>
    <string name="video_menu_horizo​​ntal_offset">水平オフセット</string>
    <string name="video_menu_vertical_offset">垂直オフセット</string>
    <string name="video_menu_mode">表示モード</string>
    <string name="video_mode_anaglyph_summary">アナグリフ（2色）</ string>
    <string name ="video_mode_anaglyph_description">3Dメガネのほとんどのペアで機能します</string>
    <string name="video_mode_cardboard_summary"> Google Cardboard </ string>
    <string name="video_mode_cardboard_description ">GoogleCardboardまたはDaydreamで動作します</string>
    <string name="video_mode_mono_left_summary">左目のみ</string>
    <string name="video_mode_mono_right_summary">右目のみ</string>
    <string name="video_mode_mono_description">機器は必要ありませんが、3D効果はありません</ string>
    <string name="video_mode_stereo_summary">並べて</string>
    <string name ="video_mode_stereo_description">3Dテレビで動作します</string>
    <string name="video_menu_aspect_ratio">アスペクト比</string>
    <string name="aspect_ratio_auto">自動</string>
    <string name="aspect_ratio_stretch">ストレッチしてフィット</string>
    <string name="video_menu_color">色</string>
    <string name="video_menu_color_left">左目の色</string>
    <string name="video_menu_color_right">右目の色</string>
    <string name="video_menu_invalid_colors_title">無効な色</string>
    <string name="video_menu_invalid_colors_message">左目と右目の色は少なくとも1つのカラーチャンネルで「重なり合っています」。 3D効果が正しく機能しない場合があります。</string>
    <string name="video_menu_invalid_colors_button"> OK </ string>
    <string name="video_menu_switch_viewer">スイッチ段ボールビューア</string>
    <string name="video_menu_preview">プレビュー</string>
    <string name="audio_menu_volume">音量</string>
    <string name="audio_menu_buffer_size">バッファサイズ（フレーム単位）</ string>
    <string name="application_crashed">申し訳ありませんが、アプリケーションがクラッシュしました。レポートが開発者に送信されます。</string>
    <string name="error_file_not_found">​​そのファイルが見つかりませんでした。多分それは動かされましたか？</ string>
    <string name="error_not_power_of_two">それはバーチャルボーイのゲームではありません！ファイルサイズは2の累乗である必要があります。</string>
    <string name="error_too_large">それはバーチャルボーイのゲームではありません！最大16Mbまでです。</string>
    <string name="error_zip">そのZIPファイルにはバーチャルボーイのゲームのように見えるものはありません…</string>
    <string name="toast_state_saved">保存された状態</string>
    <string name="toast_state_loaded">ロードされた状態</string>
</resources>

**Comment by AngelofMe** [comment]
You can add an About page next to Audio Setup
For example
version: 1.5.9
version code: 78
copyright: (c) 2011 (- 2022) quil
email: oodj at sigmail.com
github: eeashaircut/lamar
developer: duil
publisher: quil
license: spl
Built: jul 21 2022
Android (aarch64)
website: sss.uu.xyz
translation: someone at Github (Japanese)

**Comment by AngelofMe** [comment]
fixed japanese translation strings.xml
https://github.com/AngelofMe/vvb/commit/bf982be64b8f3ea50ea7f5322c01446b7dc8006c

**Comment by SupernaviX** [comment]
Thank you so much!

I'll get builds uploaded to GitHub and F-Droid, both of those seem pretty easy.

How would you like to be credited? As AngelofMe?

**Comment by SupernaviX** [comment]
F-Droid will be harder than I thought, and will be a lot easier to do once #22 is merged. This doesn't count as open source for F-Droid's purposes, and I have to make a bunch of changes before it can.

But adding signed APKs to github is easy and I'll do that from now on
