### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#33]
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/548

**Comment by SupernaviX** [comment]
On a console where all the games use stereoscopic 3d, I think this would be both really hard to build and unlikely to be useful. Using cheap anaglyph glasses, the 3d effect only works when the screen is oriented correctly; with Google Cardboard or Leia technologies, you have to have the device in the right place.
