### ISSUE TITLE
remove created by

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#38]
Display multiple duplicates that take up a lot of memory
Created by
によって作成されました

BLOX
KR155Eによって作成されました

BLOX 2
KR155Eによって作成されました

I think this is better

**BLOX**
KR155E

**BLOX 2**
KR155E

![Screenshot_20220814-152159_Trebuchet](https://user-images.githubusercontent.com/26894447/184526890-7d3c9a16-3d09-4703-86d1-c47859cf1066.png)

**Comment by AngelofMe** [comment]
or like this
creator 1
> game 1
> game 2
> game 3

creator 2
> game 1
> game 2

creator 1 and 2
> game 1

**Comment by SupernaviX** [comment]
I don't think it's important to keep it short. Look, it goes onto another line if the text gets too long.
![studio64_o458NvaBpj](https://user-images.githubusercontent.com/1137435/185807757-b9f74732-2f67-4483-ba9e-4a5de34eef0b.png)
