### ISSUE TITLE
display long file names

### ISSUE THREAD

**Issue by soundsnow** [SupernaviX/vvb#45]
SD Gundam - Dimension War (Japan) [T-En by Greg Stevens & Benjamin Stevens v1.0]
Space Squash (Japan) [T-En by Feel & Greg Stevens & Benjamin Stevens & Thunderstruck v2.0]
Virtual Fishing (Japan) [T-En by Benjamin Stevens & Thunderstruck v1.0]

![image47](https://user-images.githubusercontent.com/109885044/188256413-08256e46-e92c-43fd-8a8d-c125d9b0f016.png)
so, which is better?
![image48](https://user-images.githubusercontent.com/109885044/188258885-0bda9b52-f856-47a2-a273-8b3414264d48.png)
![image49](https://user-images.githubusercontent.com/109885044/188258887-da790037-686f-41ea-847a-541d0aa1f0b1.png)

**Comment by SupernaviX** [comment]
Made it wrap. It's pretty ugly, but functional.

![it wraps](https://i.imgur.com/xcHjOol.png)
