### ISSUE TITLE
time format and remove some known or duplicate text

### ISSUE THREAD

**Issue by soundsnow** [SupernaviX/vvb#49]
Empty slots do not show the date, the slot that shows the date must have been saved
The timing of these two slots is completely different
2022-10-13 20:39:06
2022-10-13 20:39:54
![image116](https://user-images.githubusercontent.com/109885044/195602623-c7aab1d5-bc92-48e7-b911-774424979076.png)
![Screenshot_20221013-192634_Trebuchet](https://user-images.githubusercontent.com/109885044/195602740-40c8c6c0-c176-4acd-bfb8-a3204de12f58.png)

**Comment by SupernaviX** [comment]
Fixing the datetime format was easy enough, did it [here](https://github.com/SupernaviX/vvb/commit/c1608086c39bb63182149f10643bae45f399cdf5)

I think the duplicate "Slot" is a good thing though. There's a lot of space on that screen, and longer descriptions help make the list entries "something you can obviously tap"
