### ISSUE TITLE
I added VVB on EmuGen Wiki

### ISSUE THREAD

**Issue by AngelofMe** [SupernaviX/vvb#9]
It's a good emulator but I can't see it from Emulation General Wiki, so I did this.
[Emulators on Android](https://emulation.gametechwiki.com/index.php/Emulators_on_Android) 
[Page history](https://emulation.gametechwiki.com/index.php/Special:MobileDiff/45427) 

| {{✓}}
| {{✓}}<small> (libretro)</small>
| {{✓}}
|-
| Virtual Virtual Boy
|[https://github.com/SupernaviX/vvb git][https://play.google.com/store/apps/details?id=com.simongellis.vvb 1.8.0]
| {{✓}}
| {{✗}}
| {{✓}}
| {{✓}}
|-
|Virtual Virtual Boy
|[[Virtual Boy emulators|VB]]
|[https://github.com/CidVonHighwindSupernaviX/VirtualBoyGo vvb git][https://play.google.com/store/apps/details?id=com.simongellis.vvb 1.78.10]
|Oculus Quest, Oculus Go
|{{✓}}
|VirtualBoyGo
|[[Virtual Boy emulators|VB]]
|[https://github.com/SupernaviXCidVonHighwind/vvb VirtualBoyGo git]
|Oculus Quest, Oculus Go
|{{✓}}

[Virtual Boy emulators](https://emulation.gametechwiki.com/index.php/Virtual_Boy_emulators) 
[Page history](https://emulation.gametechwiki.com/index.php/Special:MobileDiff/45428) 

|{{✓}}
|{{✓}}
|-
| Virtual Virtual Boy
|align=left|{{Icon|Android}}
|[https://github.com/SupernaviX/vvb git][https://play.google.com/store/apps/details?id=com.simongellis.vvb 1.8.0]
| {{✗}}
| {{✓}}
| {{✓}}
| {{✓}}
|-
!colspan="7"|Console

**Comment by SupernaviX** [comment]
Thank you!

Just curious, I see that you added it as "Recommended" in the "Virtual Boy emulators" section on that page, but in the "Emulators with VR support" section it's not. Any idea what "Recommended" means there?

**Comment by AngelofMe** [comment]
> Thank you!
> 
> Just curious, I see that you added it as "Recommended" in the "Virtual Boy emulators" section on that page, but in the "Emulators with VR support" section it's not. Any idea what "Recommended" means there?

I don't know what's VR. So I'm not sure.
